spring:
  application:
    name: seata-study
  datasource:
    url: jdbc:postgresql://localhost:5432/seata_study
    username: root
    password: root
#  datasource:
#    url: jdbc:mysql://localhost:3306/seata_study
#    username: root
#    password: password
  jpa:
    hibernate:
      ddl-auto: update

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seata_study_group
  service:
    vgroup-mapping:
      seata_study_group: seata-server
    grouplist:
      seata-server: 127.0.0.1:8091
  registry:
    type: file
  config:
    type: file
  enable-auto-data-source-proxy: false
  client:
    load-balance:
      type: RandomLoadBalance
  data-source-proxy-mode: AT
logging:
  level:
    root: info
